# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/francescostella/Documents/GitHub/ProgettoDEA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/francescostella/Documents/GitHub/ProgettoDEA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/francescostella/Documents/GitHub/ProgettoDEA/CMakeFiles /Users/francescostella/Documents/GitHub/ProgettoDEA//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/francescostella/Documents/GitHub/ProgettoDEA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Board

# Build rule for target.
Board: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Board
.PHONY : Board

# fast build rule for target.
Board/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Board.dir/build.make CMakeFiles/Board.dir/build
.PHONY : Board/fast

#=============================================================================
# Target rules for targets named King

# Build rule for target.
King: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 King
.PHONY : King

# fast build rule for target.
King/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/King.dir/build.make CMakeFiles/King.dir/build
.PHONY : King/fast

#=============================================================================
# Target rules for targets named Knight

# Build rule for target.
Knight: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Knight
.PHONY : Knight

# fast build rule for target.
Knight/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Knight.dir/build.make CMakeFiles/Knight.dir/build
.PHONY : Knight/fast

#=============================================================================
# Target rules for targets named Pawn

# Build rule for target.
Pawn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pawn
.PHONY : Pawn

# fast build rule for target.
Pawn/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pawn.dir/build.make CMakeFiles/Pawn.dir/build
.PHONY : Pawn/fast

#=============================================================================
# Target rules for targets named Piece

# Build rule for target.
Piece: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Piece
.PHONY : Piece

# fast build rule for target.
Piece/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Piece.dir/build.make CMakeFiles/Piece.dir/build
.PHONY : Piece/fast

#=============================================================================
# Target rules for targets named Rook

# Build rule for target.
Rook: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Rook
.PHONY : Rook

# fast build rule for target.
Rook/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rook.dir/build.make CMakeFiles/Rook.dir/build
.PHONY : Rook/fast

#=============================================================================
# Target rules for targets named Bishop

# Build rule for target.
Bishop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Bishop
.PHONY : Bishop

# fast build rule for target.
Bishop/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bishop.dir/build.make CMakeFiles/Bishop.dir/build
.PHONY : Bishop/fast

#=============================================================================
# Target rules for targets named Queen

# Build rule for target.
Queen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Queen
.PHONY : Queen

# fast build rule for target.
Queen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Queen.dir/build.make CMakeFiles/Queen.dir/build
.PHONY : Queen/fast

#=============================================================================
# Target rules for targets named Logger

# Build rule for target.
Logger: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Logger
.PHONY : Logger

# fast build rule for target.
Logger/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Logger.dir/build.make CMakeFiles/Logger.dir/build
.PHONY : Logger/fast

#=============================================================================
# Target rules for targets named Player

# Build rule for target.
Player: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Player
.PHONY : Player

# fast build rule for target.
Player/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Player.dir/build.make CMakeFiles/Player.dir/build
.PHONY : Player/fast

#=============================================================================
# Target rules for targets named Computer

# Build rule for target.
Computer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Computer
.PHONY : Computer

# fast build rule for target.
Computer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Computer.dir/build.make CMakeFiles/Computer.dir/build
.PHONY : Computer/fast

#=============================================================================
# Target rules for targets named Human

# Build rule for target.
Human: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Human
.PHONY : Human

# fast build rule for target.
Human/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Human.dir/build.make CMakeFiles/Human.dir/build
.PHONY : Human/fast

#=============================================================================
# Target rules for targets named scacchiera

# Build rule for target.
scacchiera: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scacchiera
.PHONY : scacchiera

# fast build rule for target.
scacchiera/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/build
.PHONY : scacchiera/fast

#=============================================================================
# Target rules for targets named replay

# Build rule for target.
replay: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 replay
.PHONY : replay

# fast build rule for target.
replay/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/build
.PHONY : replay/fast

src/Bishop.o: src/Bishop.cpp.o
.PHONY : src/Bishop.o

# target to build an object file
src/Bishop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bishop.dir/build.make CMakeFiles/Bishop.dir/src/Bishop.cpp.o
.PHONY : src/Bishop.cpp.o

src/Bishop.i: src/Bishop.cpp.i
.PHONY : src/Bishop.i

# target to preprocess a source file
src/Bishop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bishop.dir/build.make CMakeFiles/Bishop.dir/src/Bishop.cpp.i
.PHONY : src/Bishop.cpp.i

src/Bishop.s: src/Bishop.cpp.s
.PHONY : src/Bishop.s

# target to generate assembly for a file
src/Bishop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Bishop.dir/build.make CMakeFiles/Bishop.dir/src/Bishop.cpp.s
.PHONY : src/Bishop.cpp.s

src/Board.o: src/Board.cpp.o
.PHONY : src/Board.o

# target to build an object file
src/Board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Board.dir/build.make CMakeFiles/Board.dir/src/Board.cpp.o
.PHONY : src/Board.cpp.o

src/Board.i: src/Board.cpp.i
.PHONY : src/Board.i

# target to preprocess a source file
src/Board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Board.dir/build.make CMakeFiles/Board.dir/src/Board.cpp.i
.PHONY : src/Board.cpp.i

src/Board.s: src/Board.cpp.s
.PHONY : src/Board.s

# target to generate assembly for a file
src/Board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Board.dir/build.make CMakeFiles/Board.dir/src/Board.cpp.s
.PHONY : src/Board.cpp.s

src/Computer.o: src/Computer.cpp.o
.PHONY : src/Computer.o

# target to build an object file
src/Computer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Computer.dir/build.make CMakeFiles/Computer.dir/src/Computer.cpp.o
.PHONY : src/Computer.cpp.o

src/Computer.i: src/Computer.cpp.i
.PHONY : src/Computer.i

# target to preprocess a source file
src/Computer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Computer.dir/build.make CMakeFiles/Computer.dir/src/Computer.cpp.i
.PHONY : src/Computer.cpp.i

src/Computer.s: src/Computer.cpp.s
.PHONY : src/Computer.s

# target to generate assembly for a file
src/Computer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Computer.dir/build.make CMakeFiles/Computer.dir/src/Computer.cpp.s
.PHONY : src/Computer.cpp.s

src/Human.o: src/Human.cpp.o
.PHONY : src/Human.o

# target to build an object file
src/Human.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Human.dir/build.make CMakeFiles/Human.dir/src/Human.cpp.o
.PHONY : src/Human.cpp.o

src/Human.i: src/Human.cpp.i
.PHONY : src/Human.i

# target to preprocess a source file
src/Human.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Human.dir/build.make CMakeFiles/Human.dir/src/Human.cpp.i
.PHONY : src/Human.cpp.i

src/Human.s: src/Human.cpp.s
.PHONY : src/Human.s

# target to generate assembly for a file
src/Human.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Human.dir/build.make CMakeFiles/Human.dir/src/Human.cpp.s
.PHONY : src/Human.cpp.s

src/King.o: src/King.cpp.o
.PHONY : src/King.o

# target to build an object file
src/King.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/King.dir/build.make CMakeFiles/King.dir/src/King.cpp.o
.PHONY : src/King.cpp.o

src/King.i: src/King.cpp.i
.PHONY : src/King.i

# target to preprocess a source file
src/King.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/King.dir/build.make CMakeFiles/King.dir/src/King.cpp.i
.PHONY : src/King.cpp.i

src/King.s: src/King.cpp.s
.PHONY : src/King.s

# target to generate assembly for a file
src/King.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/King.dir/build.make CMakeFiles/King.dir/src/King.cpp.s
.PHONY : src/King.cpp.s

src/Knight.o: src/Knight.cpp.o
.PHONY : src/Knight.o

# target to build an object file
src/Knight.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Knight.dir/build.make CMakeFiles/Knight.dir/src/Knight.cpp.o
.PHONY : src/Knight.cpp.o

src/Knight.i: src/Knight.cpp.i
.PHONY : src/Knight.i

# target to preprocess a source file
src/Knight.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Knight.dir/build.make CMakeFiles/Knight.dir/src/Knight.cpp.i
.PHONY : src/Knight.cpp.i

src/Knight.s: src/Knight.cpp.s
.PHONY : src/Knight.s

# target to generate assembly for a file
src/Knight.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Knight.dir/build.make CMakeFiles/Knight.dir/src/Knight.cpp.s
.PHONY : src/Knight.cpp.s

src/Logger.o: src/Logger.cpp.o
.PHONY : src/Logger.o

# target to build an object file
src/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Logger.dir/build.make CMakeFiles/Logger.dir/src/Logger.cpp.o
.PHONY : src/Logger.cpp.o

src/Logger.i: src/Logger.cpp.i
.PHONY : src/Logger.i

# target to preprocess a source file
src/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Logger.dir/build.make CMakeFiles/Logger.dir/src/Logger.cpp.i
.PHONY : src/Logger.cpp.i

src/Logger.s: src/Logger.cpp.s
.PHONY : src/Logger.s

# target to generate assembly for a file
src/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Logger.dir/build.make CMakeFiles/Logger.dir/src/Logger.cpp.s
.PHONY : src/Logger.cpp.s

src/Pawn.o: src/Pawn.cpp.o
.PHONY : src/Pawn.o

# target to build an object file
src/Pawn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pawn.dir/build.make CMakeFiles/Pawn.dir/src/Pawn.cpp.o
.PHONY : src/Pawn.cpp.o

src/Pawn.i: src/Pawn.cpp.i
.PHONY : src/Pawn.i

# target to preprocess a source file
src/Pawn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pawn.dir/build.make CMakeFiles/Pawn.dir/src/Pawn.cpp.i
.PHONY : src/Pawn.cpp.i

src/Pawn.s: src/Pawn.cpp.s
.PHONY : src/Pawn.s

# target to generate assembly for a file
src/Pawn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pawn.dir/build.make CMakeFiles/Pawn.dir/src/Pawn.cpp.s
.PHONY : src/Pawn.cpp.s

src/Piece.o: src/Piece.cpp.o
.PHONY : src/Piece.o

# target to build an object file
src/Piece.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Piece.dir/build.make CMakeFiles/Piece.dir/src/Piece.cpp.o
.PHONY : src/Piece.cpp.o

src/Piece.i: src/Piece.cpp.i
.PHONY : src/Piece.i

# target to preprocess a source file
src/Piece.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Piece.dir/build.make CMakeFiles/Piece.dir/src/Piece.cpp.i
.PHONY : src/Piece.cpp.i

src/Piece.s: src/Piece.cpp.s
.PHONY : src/Piece.s

# target to generate assembly for a file
src/Piece.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Piece.dir/build.make CMakeFiles/Piece.dir/src/Piece.cpp.s
.PHONY : src/Piece.cpp.s

src/Player.o: src/Player.cpp.o
.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Player.dir/build.make CMakeFiles/Player.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i
.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Player.dir/build.make CMakeFiles/Player.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s
.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Player.dir/build.make CMakeFiles/Player.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/Queen.o: src/Queen.cpp.o
.PHONY : src/Queen.o

# target to build an object file
src/Queen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Queen.dir/build.make CMakeFiles/Queen.dir/src/Queen.cpp.o
.PHONY : src/Queen.cpp.o

src/Queen.i: src/Queen.cpp.i
.PHONY : src/Queen.i

# target to preprocess a source file
src/Queen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Queen.dir/build.make CMakeFiles/Queen.dir/src/Queen.cpp.i
.PHONY : src/Queen.cpp.i

src/Queen.s: src/Queen.cpp.s
.PHONY : src/Queen.s

# target to generate assembly for a file
src/Queen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Queen.dir/build.make CMakeFiles/Queen.dir/src/Queen.cpp.s
.PHONY : src/Queen.cpp.s

src/Rook.o: src/Rook.cpp.o
.PHONY : src/Rook.o

# target to build an object file
src/Rook.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rook.dir/build.make CMakeFiles/Rook.dir/src/Rook.cpp.o
.PHONY : src/Rook.cpp.o

src/Rook.i: src/Rook.cpp.i
.PHONY : src/Rook.i

# target to preprocess a source file
src/Rook.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rook.dir/build.make CMakeFiles/Rook.dir/src/Rook.cpp.i
.PHONY : src/Rook.cpp.i

src/Rook.s: src/Rook.cpp.s
.PHONY : src/Rook.s

# target to generate assembly for a file
src/Rook.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Rook.dir/build.make CMakeFiles/Rook.dir/src/Rook.cpp.s
.PHONY : src/Rook.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/main_replay.o: src/main_replay.cpp.o
.PHONY : src/main_replay.o

# target to build an object file
src/main_replay.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/main_replay.cpp.o
.PHONY : src/main_replay.cpp.o

src/main_replay.i: src/main_replay.cpp.i
.PHONY : src/main_replay.i

# target to preprocess a source file
src/main_replay.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/main_replay.cpp.i
.PHONY : src/main_replay.cpp.i

src/main_replay.s: src/main_replay.cpp.s
.PHONY : src/main_replay.s

# target to generate assembly for a file
src/main_replay.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/main_replay.cpp.s
.PHONY : src/main_replay.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Bishop"
	@echo "... Board"
	@echo "... Computer"
	@echo "... Human"
	@echo "... King"
	@echo "... Knight"
	@echo "... Logger"
	@echo "... Pawn"
	@echo "... Piece"
	@echo "... Player"
	@echo "... Queen"
	@echo "... Rook"
	@echo "... replay"
	@echo "... scacchiera"
	@echo "... src/Bishop.o"
	@echo "... src/Bishop.i"
	@echo "... src/Bishop.s"
	@echo "... src/Board.o"
	@echo "... src/Board.i"
	@echo "... src/Board.s"
	@echo "... src/Computer.o"
	@echo "... src/Computer.i"
	@echo "... src/Computer.s"
	@echo "... src/Human.o"
	@echo "... src/Human.i"
	@echo "... src/Human.s"
	@echo "... src/King.o"
	@echo "... src/King.i"
	@echo "... src/King.s"
	@echo "... src/Knight.o"
	@echo "... src/Knight.i"
	@echo "... src/Knight.s"
	@echo "... src/Logger.o"
	@echo "... src/Logger.i"
	@echo "... src/Logger.s"
	@echo "... src/Pawn.o"
	@echo "... src/Pawn.i"
	@echo "... src/Pawn.s"
	@echo "... src/Piece.o"
	@echo "... src/Piece.i"
	@echo "... src/Piece.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/Queen.o"
	@echo "... src/Queen.i"
	@echo "... src/Queen.s"
	@echo "... src/Rook.o"
	@echo "... src/Rook.i"
	@echo "... src/Rook.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/main_replay.o"
	@echo "... src/main_replay.i"
	@echo "... src/main_replay.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

